### ISSUE TITLE
workshop feedback

### ISSUE THREAD

**Issue by edublancas** [ploomber/latam-ai#2]
* Let's take people to the workshop.md, no need to take them to the readme.md
* since the README.md will most likely only ve visited from github, let's change the newsletter HTML for a direct link: https://www.getrevue.co/profile/ploomber and just tell people "if you want to get updates, subscribe"
* the top of the workshop.md looks pretty busy, I think let's remove the setup section (it's in the README.md anyway). If people get to this stage, we can assume they already configured their environment
* when I open the workshop.md in binder, the %%bash magics do not appear:

![image](https://user-images.githubusercontent.com/989250/187341669-bcdfbcf1-7582-4435-af3c-048d17dab3de.png)

hence, the cells wont run. this can be fixed by adding jupytext metadata at the top of the file. add this to the top of workshop.md

```md
---
jupyter:
  jupytext:
    text_representation:
      extension: .md
      format_name: markdown
      format_version: '1.3'
      jupytext_version: 1.13.6
  kernelspec:
    display_name: Python 3 (ipykernel)
    language: python
    name: python3
---
```

**Comment by edublancas** [comment]
one more thing, workshop.md top cell: the newsletter cell has "sh" as the language but it should be "python":

![image](https://user-images.githubusercontent.com/989250/187342129-8af06c4a-a6c8-4995-ab55-e55213a46c82.png)

**Comment by RodolfoFerro** [comment]
Done in #3
